"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var app_server_1 = require("./lib/app-server");
var health_server_1 = require("./lib/health-server");
var APP_PORT = parseInt(process.env.PORT || '3000', 10);
var HEALTH_PORT = parseInt(process.env.PORT || '3001', 10);
var appServer = app_server_1.default();
var healthServer = health_server_1.default();
appServer.listen(APP_PORT, function () { return console.log('App server listening on port ', APP_PORT); });
healthServer.listen(HEALTH_PORT, function () { return console.log('Health server listening on port ', HEALTH_PORT); });
